2015-11-06 07:58:29 Error: Fatal Error (4): syntax error, unexpected 'return' (T_RETURN) in [C:\xampp\htdocs\assignment\src\Model\Table\OrdersTable.php, line 19]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-06 07:58:30 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'return' (T_RETURN)
Request URL: /assignment/orders
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-06 07:59:47 Warning: Warning (4096): Argument 1 passed to App\Model\Table\OrdersTable::validationDefault() must be an instance of App\Model\Table\Validator, instance of Cake\Validation\Validator given, called in C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\ValidatorAwareTrait.php on line 106 and defined in [C:\xampp\htdocs\assignment\src\Model\Table\OrdersTable.php, line 12]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Model\Table\OrdersTable::validationDefault() - APP/Model\Table\OrdersTable.php, line 12
Cake\ORM\Table::validator() - CORE\src\Validation\ValidatorAwareTrait.php, line 106
Cake\View\Form\EntityContext::_getValidator() - CORE\src\View\Form\EntityContext.php, line 404
Cake\View\Form\EntityContext::isRequired() - CORE\src\View\Form\EntityContext.php, line 350
Cake\View\Helper\FormHelper::_magicOptions() - CORE\src\View\Helper\FormHelper.php, line 1251
Cake\View\Helper\FormHelper::_parseOptions() - CORE\src\View\Helper\FormHelper.php, line 1152
Cake\View\Helper\FormHelper::input() - CORE\src\View\Helper\FormHelper.php, line 1007
include - APP/Template\Orders\add.ctp, line 6
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 972
Cake\View\View::_render() - CORE\src\View\View.php, line 932
Cake\View\View::render() - CORE\src\View\View.php, line 580
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 598
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 120
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-06 08:00:02 Warning: Warning (4096): Argument 1 passed to App\Model\Table\OrdersTable::validationDefault() must be an instance of App\Model\Table\Validator, instance of Cake\Validation\Validator given, called in C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\ValidatorAwareTrait.php on line 106 and defined in [C:\xampp\htdocs\assignment\src\Model\Table\OrdersTable.php, line 12]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Model\Table\OrdersTable::validationDefault() - APP/Model\Table\OrdersTable.php, line 12
Cake\ORM\Table::validator() - CORE\src\Validation\ValidatorAwareTrait.php, line 106
Cake\View\Form\EntityContext::_getValidator() - CORE\src\View\Form\EntityContext.php, line 404
Cake\View\Form\EntityContext::isRequired() - CORE\src\View\Form\EntityContext.php, line 350
Cake\View\Helper\FormHelper::_magicOptions() - CORE\src\View\Helper\FormHelper.php, line 1251
Cake\View\Helper\FormHelper::_parseOptions() - CORE\src\View\Helper\FormHelper.php, line 1152
Cake\View\Helper\FormHelper::input() - CORE\src\View\Helper\FormHelper.php, line 1007
include - APP/Template\Orders\add.ctp, line 6
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 972
Cake\View\View::_render() - CORE\src\View\View.php, line 932
Cake\View\View::render() - CORE\src\View\View.php, line 580
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 598
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 120
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-06 08:06:39 Error: Fatal Error (4): syntax error, unexpected '?>', expecting function (T_FUNCTION) in [C:\xampp\htdocs\assignment\src\Controller\OrdersController.php, line 58]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-06 08:06:39 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '?>', expecting function (T_FUNCTION)
Request URL: /assignment/orders
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 58)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-06 08:07:05 Error: Fatal Error (4): syntax error, unexpected '?>', expecting function (T_FUNCTION) in [C:\xampp\htdocs\assignment\src\Controller\OrdersController.php, line 58]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-06 08:07:06 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '?>', expecting function (T_FUNCTION)
Request URL: /assignment/orders
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 58)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-06 08:07:15 Error: Fatal Error (4): syntax error, unexpected '?>', expecting function (T_FUNCTION) in [C:\xampp\htdocs\assignment\src\Controller\OrdersController.php, line 58]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-06 08:07:15 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '?>', expecting function (T_FUNCTION)
Request URL: /assignment/orders
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 58)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 04:41:00 Error: Fatal Error (4): syntax error, unexpected 'onion' (T_STRING) in [C:\xampp\htdocs\assignment\src\Template\Orders\add.ctp, line 17]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 04:41:01 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'onion' (T_STRING)
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 04:47:44 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\assignment\src\Template\Orders\add.ctp, line 19]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 04:47:44 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ';'
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 04:48:42 Error: Fatal Error (4): syntax error, unexpected ')' in [C:\xampp\htdocs\assignment\src\Template\Orders\add.ctp, line 28]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 04:48:43 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ')'
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 28)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 04:53:49 Error: Fatal Error (4): syntax error, unexpected ''Value 1'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in [C:\xampp\htdocs\assignment\src\Template\Orders\add.ctp, line 29]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 04:53:50 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ''Value 1'' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 29)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 04:59:23 Error: Fatal Error (4): syntax error, unexpected 'Value' (T_STRING), expecting ')' in [C:\xampp\htdocs\assignment\src\Template\Orders\add.ctp, line 22]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 04:59:23 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'Value' (T_STRING), expecting ')'
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 22)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 05:28:56 Error: Fatal Error (4): syntax error, unexpected ''Value 2'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in [C:\xampp\htdocs\assignment\src\Template\Orders\add.ctp, line 25]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 05:28:56 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ''Value 2'' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 05:31:53 Error: Fatal Error (4): syntax error, unexpected ''Value 2'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in [C:\xampp\htdocs\assignment\src\Template\Orders\add.ctp, line 25]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 05:31:55 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ''Value 2'' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 05:32:31 Error: Fatal Error (4): syntax error, unexpected ''Value 2'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in [C:\xampp\htdocs\assignment\src\Template\Orders\add.ctp, line 25]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 05:32:31 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ''Value 2'' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 05:34:14 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW) in [C:\xampp\htdocs\assignment\src\Template\Orders\add.ctp, line 37]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 05:34:14 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW)
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 37)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 05:34:26 Error: Fatal Error (4): syntax error, unexpected '=' in [C:\xampp\htdocs\assignment\src\Template\Orders\add.ctp, line 37]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 05:34:27 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '='
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 37)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 05:35:12 Error: Fatal Error (4): syntax error, unexpected '=', expecting ')' in [C:\xampp\htdocs\assignment\src\Template\Orders\add.ctp, line 38]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 05:35:13 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=', expecting ')'
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 38)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 05:59:09 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\assignment\src\Model\Table\OrdersTable.php, line 18]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 05:59:10 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 06:03:38 Error: Fatal Error (4): syntax error, unexpected ''email'' (T_CONSTANT_ENCAPSED_STRING) in [C:\xampp\htdocs\assignment\src\Model\Table\OrdersTable.php, line 28]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 06:03:38 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ''email'' (T_CONSTANT_ENCAPSED_STRING)
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 28)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 06:11:47 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [C:\xampp\htdocs\assignment\src\Model\Table\OrdersTable.php, line 15]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 06:11:47 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 06:12:13 Error: Fatal Error (4): syntax error, unexpected '?>', expecting function (T_FUNCTION) in [C:\xampp\htdocs\assignment\src\Model\Table\OrdersTable.php, line 24]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 06:12:14 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '?>', expecting function (T_FUNCTION)
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 06:12:52 Error: Fatal Error (1): Call to a member function provider() on a non-object in [C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\ValidatorAwareTrait.php, line 112]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 06:12:53 Error: [Cake\Error\FatalErrorException] Call to a member function provider() on a non-object
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 112)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 06:13:42 Error: Fatal Error (1): Call to a member function provider() on a non-object in [C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\ValidatorAwareTrait.php, line 112]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 06:13:43 Error: [Cake\Error\FatalErrorException] Call to a member function provider() on a non-object
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 112)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 06:22:11 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\assignment\src\Model\Table\OrdersTable.php, line 35]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 06:22:12 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 35)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 06:23:42 Error: [ReflectionException] Method ^\d{3}\-\d{3}\-\d{4}$/ does not exist
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\RulesProvider.php(64): ReflectionClass->getMethod('^\\d{3}\\-\\d{3}\\-...')
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\ValidationRule.php(140): Cake\Validation\RulesProvider->__call('^\\d{3}\\-\\d{3}\\-...', Array)
#2 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\ValidationRule.php(140): Cake\Validation\RulesProvider->^\d{3}\-\d{3}\-\d{4}$/('21312324324', Array)
#3 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\Validator.php(656): Cake\Validation\ValidationRule->process('21312324324', Array, Array)
#4 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\Validator.php(136): Cake\Validation\Validator->_processRules('telephone', Object(Cake\Validation\ValidationSet), Array, true)
#5 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\ORM\Marshaller.php(181): Cake\Validation\Validator->errors(Array, true)
#6 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\ORM\Marshaller.php(437): Cake\ORM\Marshaller->_validate(Array, Array, true)
#7 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\ORM\Table.php(2033): Cake\ORM\Marshaller->merge(Object(Cake\ORM\Entity), Array, Array)
#8 C:\xampp\htdocs\assignment\src\Controller\OrdersController.php(25): Cake\ORM\Table->patchEntity(Object(Cake\ORM\Entity), Array)
#9 [internal function]: App\Controller\OrdersController->add()
#10 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#12 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#13 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#14 {main}


2015-11-07 06:24:29 Error: [ReflectionException] Method ^\d{3}\-\d{3}\-\d{4}$/I does not exist
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\RulesProvider.php(64): ReflectionClass->getMethod('^\\d{3}\\-\\d{3}\\-...')
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\ValidationRule.php(140): Cake\Validation\RulesProvider->__call('^\\d{3}\\-\\d{3}\\-...', Array)
#2 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\ValidationRule.php(140): Cake\Validation\RulesProvider->^\d{3}\-\d{3}\-\d{4}$/I('21312324324', Array)
#3 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\Validator.php(656): Cake\Validation\ValidationRule->process('21312324324', Array, Array)
#4 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\Validator.php(136): Cake\Validation\Validator->_processRules('telephone', Object(Cake\Validation\ValidationSet), Array, true)
#5 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\ORM\Marshaller.php(181): Cake\Validation\Validator->errors(Array, true)
#6 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\ORM\Marshaller.php(437): Cake\ORM\Marshaller->_validate(Array, Array, true)
#7 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\ORM\Table.php(2033): Cake\ORM\Marshaller->merge(Object(Cake\ORM\Entity), Array, Array)
#8 C:\xampp\htdocs\assignment\src\Controller\OrdersController.php(25): Cake\ORM\Table->patchEntity(Object(Cake\ORM\Entity), Array)
#9 [internal function]: App\Controller\OrdersController->add()
#10 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#12 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#13 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#14 {main}


2015-11-07 06:25:31 Error: [ReflectionException] Method d{3}\-\d{3}\-\d{4} does not exist
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\RulesProvider.php(64): ReflectionClass->getMethod('d{3}\\-\\d{3}\\-\\d...')
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\ValidationRule.php(140): Cake\Validation\RulesProvider->__call('d{3}\\-\\d{3}\\-\\d...', Array)
#2 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\ValidationRule.php(140): Cake\Validation\RulesProvider->d{3}\-\d{3}\-\d{4}('21312324324', Array)
#3 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\Validator.php(656): Cake\Validation\ValidationRule->process('21312324324', Array, Array)
#4 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\Validator.php(136): Cake\Validation\Validator->_processRules('telephone', Object(Cake\Validation\ValidationSet), Array, true)
#5 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\ORM\Marshaller.php(181): Cake\Validation\Validator->errors(Array, true)
#6 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\ORM\Marshaller.php(437): Cake\ORM\Marshaller->_validate(Array, Array, true)
#7 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\ORM\Table.php(2033): Cake\ORM\Marshaller->merge(Object(Cake\ORM\Entity), Array, Array)
#8 C:\xampp\htdocs\assignment\src\Controller\OrdersController.php(25): Cake\ORM\Table->patchEntity(Object(Cake\ORM\Entity), Array)
#9 [internal function]: App\Controller\OrdersController->add()
#10 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#12 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#13 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#14 {main}


2015-11-07 06:26:17 Error: [ReflectionException] Method [d{3}\-\d{3}\-\d{4}] does not exist
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\RulesProvider.php(64): ReflectionClass->getMethod('[d{3}\\-\\d{3}\\-\\...')
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\ValidationRule.php(140): Cake\Validation\RulesProvider->__call('[d{3}\\-\\d{3}\\-\\...', Array)
#2 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\ValidationRule.php(140): Cake\Validation\RulesProvider->[d{3}\-\d{3}\-\d{4}]('21312324324', Array)
#3 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\Validator.php(656): Cake\Validation\ValidationRule->process('21312324324', Array, Array)
#4 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\Validator.php(136): Cake\Validation\Validator->_processRules('telephone', Object(Cake\Validation\ValidationSet), Array, true)
#5 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\ORM\Marshaller.php(181): Cake\Validation\Validator->errors(Array, true)
#6 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\ORM\Marshaller.php(437): Cake\ORM\Marshaller->_validate(Array, Array, true)
#7 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\ORM\Table.php(2033): Cake\ORM\Marshaller->merge(Object(Cake\ORM\Entity), Array, Array)
#8 C:\xampp\htdocs\assignment\src\Controller\OrdersController.php(25): Cake\ORM\Table->patchEntity(Object(Cake\ORM\Entity), Array)
#9 [internal function]: App\Controller\OrdersController->add()
#10 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#12 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#13 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#14 {main}


2015-11-07 06:27:06 Error: [ReflectionException] Method [d{3}\-\d{3}\-\d{4}]+ does not exist
Request URL: /assignment/orders/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\RulesProvider.php(64): ReflectionClass->getMethod('[d{3}\\-\\d{3}\\-\\...')
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\ValidationRule.php(140): Cake\Validation\RulesProvider->__call('[d{3}\\-\\d{3}\\-\\...', Array)
#2 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\ValidationRule.php(140): Cake\Validation\RulesProvider->[d{3}\-\d{3}\-\d{4}]+('21312324324', Array)
#3 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\Validator.php(656): Cake\Validation\ValidationRule->process('21312324324', Array, Array)
#4 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\Validator.php(136): Cake\Validation\Validator->_processRules('telephone', Object(Cake\Validation\ValidationSet), Array, true)
#5 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\ORM\Marshaller.php(181): Cake\Validation\Validator->errors(Array, true)
#6 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\ORM\Marshaller.php(437): Cake\ORM\Marshaller->_validate(Array, Array, true)
#7 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\ORM\Table.php(2033): Cake\ORM\Marshaller->merge(Object(Cake\ORM\Entity), Array, Array)
#8 C:\xampp\htdocs\assignment\src\Controller\OrdersController.php(25): Cake\ORM\Table->patchEntity(Object(Cake\ORM\Entity), Array)
#9 [internal function]: App\Controller\OrdersController->add()
#10 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#12 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#13 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#14 {main}


2015-11-07 06:30:39 Warning: Warning (2): preg_match(): No ending delimiter '^' found in [C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\Validation.php, line 830]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
preg_match - [internal], line ??
Cake\Validation\Validation::_check() - CORE\src\Validation\Validation.php, line 830
Cake\Validation\Validation::custom() - CORE\src\Validation\Validation.php, line 319
ReflectionMethod::invokeArgs() - [internal], line ??
Cake\Validation\RulesProvider::__call() - CORE\src\Validation\RulesProvider.php, line 70
Cake\Validation\RulesProvider::custom() - [internal], line ??
Cake\Validation\ValidationRule::process() - CORE\src\Validation\ValidationRule.php, line 138
Cake\Validation\Validator::_processRules() - CORE\src\Validation\Validator.php, line 656
Cake\Validation\Validator::errors() - CORE\src\Validation\Validator.php, line 136
Cake\ORM\Marshaller::_validate() - CORE\src\ORM\Marshaller.php, line 181
Cake\ORM\Marshaller::merge() - CORE\src\ORM\Marshaller.php, line 437
Cake\ORM\Table::patchEntity() - CORE\src\ORM\Table.php, line 2033
App\Controller\OrdersController::add() - APP/Controller\OrdersController.php, line 25
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 06:34:16 Warning: Warning (2): preg_match(): No ending delimiter '^' found in [C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\Validation.php, line 830]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
preg_match - [internal], line ??
Cake\Validation\Validation::_check() - CORE\src\Validation\Validation.php, line 830
Cake\Validation\Validation::custom() - CORE\src\Validation\Validation.php, line 319
ReflectionMethod::invokeArgs() - [internal], line ??
Cake\Validation\RulesProvider::__call() - CORE\src\Validation\RulesProvider.php, line 70
Cake\Validation\RulesProvider::custom() - [internal], line ??
Cake\Validation\ValidationRule::process() - CORE\src\Validation\ValidationRule.php, line 138
Cake\Validation\Validator::_processRules() - CORE\src\Validation\Validator.php, line 656
Cake\Validation\Validator::errors() - CORE\src\Validation\Validator.php, line 136
Cake\ORM\Marshaller::_validate() - CORE\src\ORM\Marshaller.php, line 181
Cake\ORM\Marshaller::merge() - CORE\src\ORM\Marshaller.php, line 437
Cake\ORM\Table::patchEntity() - CORE\src\ORM\Table.php, line 2033
App\Controller\OrdersController::add() - APP/Controller\OrdersController.php, line 25
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 06:36:14 Warning: Warning (2): preg_match(): Delimiter must not be alphanumeric or backslash in [C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\Validation.php, line 830]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
preg_match - [internal], line ??
Cake\Validation\Validation::_check() - CORE\src\Validation\Validation.php, line 830
Cake\Validation\Validation::custom() - CORE\src\Validation\Validation.php, line 319
ReflectionMethod::invokeArgs() - [internal], line ??
Cake\Validation\RulesProvider::__call() - CORE\src\Validation\RulesProvider.php, line 70
Cake\Validation\RulesProvider::custom() - [internal], line ??
Cake\Validation\ValidationRule::process() - CORE\src\Validation\ValidationRule.php, line 138
Cake\Validation\Validator::_processRules() - CORE\src\Validation\Validator.php, line 656
Cake\Validation\Validator::errors() - CORE\src\Validation\Validator.php, line 136
Cake\ORM\Marshaller::_validate() - CORE\src\ORM\Marshaller.php, line 181
Cake\ORM\Marshaller::merge() - CORE\src\ORM\Marshaller.php, line 437
Cake\ORM\Table::patchEntity() - CORE\src\ORM\Table.php, line 2033
App\Controller\OrdersController::add() - APP/Controller\OrdersController.php, line 25
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 06:36:33 Warning: Warning (2): preg_match(): Delimiter must not be alphanumeric or backslash in [C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Validation\Validation.php, line 830]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
preg_match - [internal], line ??
Cake\Validation\Validation::_check() - CORE\src\Validation\Validation.php, line 830
Cake\Validation\Validation::custom() - CORE\src\Validation\Validation.php, line 319
ReflectionMethod::invokeArgs() - [internal], line ??
Cake\Validation\RulesProvider::__call() - CORE\src\Validation\RulesProvider.php, line 70
Cake\Validation\RulesProvider::custom() - [internal], line ??
Cake\Validation\ValidationRule::process() - CORE\src\Validation\ValidationRule.php, line 138
Cake\Validation\Validator::_processRules() - CORE\src\Validation\Validator.php, line 656
Cake\Validation\Validator::errors() - CORE\src\Validation\Validator.php, line 136
Cake\ORM\Marshaller::_validate() - CORE\src\ORM\Marshaller.php, line 181
Cake\ORM\Marshaller::merge() - CORE\src\ORM\Marshaller.php, line 437
Cake\ORM\Table::patchEntity() - CORE\src\ORM\Table.php, line 2033
App\Controller\OrdersController::add() - APP/Controller\OrdersController.php, line 25
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 06:47:16 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Newindex could not be found.
Exception Attributes: array (
  'class' => 'Newindex',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /assignment/newindex
Stack Trace:
#0 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-07 06:48:38 Error: [Cake\Controller\Exception\MissingActionException] Action NewindexController::index() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'NewindexController',
  'action' => 'index',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /assignment/newindex
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\NewindexController))
#2 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-11-07 06:48:51 Error: [Cake\View\Exception\MissingTemplateException] Template file "Newindex\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Newindex\\index.ctp',
)
Request URL: /assignment/newindex
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\View\View.php(577): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(598): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\NewindexController))
#4 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-11-07 06:55:02 Error: [Cake\Controller\Exception\MissingActionException] Action NewindexController::add() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'NewindexController',
  'action' => 'add',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /assignment/newindex/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\NewindexController))
#2 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-11-07 06:56:02 Error: Fatal Error (1): Call to a member function newEntity() on a non-object in [C:\xampp\htdocs\assignment\src\Controller\NewindexController.php, line 14]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 06:56:02 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on a non-object
Request URL: /assignment/newindex/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 06:56:35 Error: Fatal Error (1): Call to a member function newEntity() on a non-object in [C:\xampp\htdocs\assignment\src\Controller\NewindexController.php, line 20]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 06:56:36 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on a non-object
Request URL: /assignment/newindex/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 06:57:48 Error: Fatal Error (1): Call to a member function newEntity() on a non-object in [C:\xampp\htdocs\assignment\src\Controller\NewindexController.php, line 20]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 06:57:49 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on a non-object
Request URL: /assignment/newindex/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 06:59:28 Error: [Cake\Controller\Exception\MissingActionException] Action NewindexController::add() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'NewindexController',
  'action' => 'add',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /assignment/newindex/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\NewindexController))
#2 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-11-07 06:59:41 Error: Fatal Error (1): Call to a member function newEntity() on a non-object in [C:\xampp\htdocs\assignment\src\Controller\NewindexController.php, line 20]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 06:59:42 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on a non-object
Request URL: /assignment/newindex/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 07:01:10 Error: Fatal Error (1): Call to a member function newEntity() on a non-object in [C:\xampp\htdocs\assignment\src\Controller\NewindexController.php, line 20]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 07:01:11 Error: Fatal Error (1): Call to a member function newEntity() on a non-object in [C:\xampp\htdocs\assignment\src\Controller\NewindexController.php, line 20]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 07:01:11 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on a non-object
Request URL: /assignment/newindex/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 07:01:11 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on a non-object
Request URL: /assignment/newindex/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 07:01:33 Error: Fatal Error (1): Call to a member function newEntity() on a non-object in [C:\xampp\htdocs\assignment\src\Controller\NewindexController.php, line 20]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 07:01:34 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on a non-object
Request URL: /assignment/newindex/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 07:01:36 Error: Fatal Error (1): Call to a member function newEntity() on a non-object in [C:\xampp\htdocs\assignment\src\Controller\NewindexController.php, line 20]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 07:01:36 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on a non-object
Request URL: /assignment/newindex/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 07:03:00 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Newindex could not be found.
Exception Attributes: array (
  'class' => 'Newindex',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /assignment/newindex/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-07 07:03:04 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Newindex could not be found.
Exception Attributes: array (
  'class' => 'Newindex',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /assignment/newindex/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-07 07:17:55 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\assignment\src\Template\Orders\index.ctp, line 3]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 07:17:56 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '<'
Request URL: /assignment/
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 3)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 07:17:56 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\assignment\src\Template\Orders\index.ctp, line 3]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 07:17:57 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '<'
Request URL: /assignment/
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 3)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 14:13:59 Error: Fatal Error (1): Call to a member function allow() on a non-object in [C:\xampp\htdocs\assignment\src\Controller\UsersController.php, line 13]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 14:14:00 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on a non-object
Request URL: /assignment/users
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 14:19:14 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 60]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 14:19:15 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '}'
Request URL: /assignment/users
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 60)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 14:19:34 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 61]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 14:19:34 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '}'
Request URL: /assignment/users
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 61)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 14:19:54 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:19:55 Error: [Cake\View\Exception\MissingTemplateException] Template file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /assignment/users
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\View\View.php(577): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(598): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#4 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-11-07 14:19:56 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:19:57 Error: [Cake\View\Exception\MissingTemplateException] Template file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /assignment/users
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\View\View.php(577): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(598): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#4 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-11-07 14:27:57 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:27:57 Error: [Cake\View\Exception\MissingTemplateException] Template file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /assignment/users
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\View\View.php(577): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(598): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#4 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-11-07 14:27:58 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:27:59 Error: [Cake\View\Exception\MissingTemplateException] Template file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /assignment/users
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\View\View.php(577): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(598): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#4 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-11-07 14:28:31 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:28:32 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:29:07 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:29:09 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:29:32 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:29:34 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:30:57 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:30:59 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:32:35 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:32:37 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:34:05 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:34:07 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:34:31 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:34:32 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:37:24 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, none given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:37:25 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, none given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:37:33 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, none given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:37:34 Warning: Warning (4096): Argument 1 passed to App\Controller\AppController::beforeFilter() must be an instance of App\Controller\Event, none given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 12 and defined in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 54]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 54
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:38:57 Warning: Warning (4096): Argument 1 passed to Cake\Controller\Controller::beforeFilter() must be an instance of Cake\Event\Event, none given, called in C:\xampp\htdocs\assignment\src\Controller\AppController.php on line 56 and defined in [C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php, line 713]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
Cake\Controller\Controller::beforeFilter() - CORE\src\Controller\Controller.php, line 713
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 56
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:38:58 Warning: Warning (4096): Argument 1 passed to Cake\Controller\Controller::beforeFilter() must be an instance of Cake\Event\Event, none given, called in C:\xampp\htdocs\assignment\src\Controller\AppController.php on line 56 and defined in [C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php, line 713]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
Cake\Controller\Controller::beforeFilter() - CORE\src\Controller\Controller.php, line 713
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 56
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:39:55 Warning: Warning (4096): Argument 1 passed to Cake\Controller\Controller::beforeFilter() must be an instance of Cake\Event\Event, none given, called in C:\xampp\htdocs\assignment\src\Controller\AppController.php on line 56 and defined in [C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php, line 713]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
Cake\Controller\Controller::beforeFilter() - CORE\src\Controller\Controller.php, line 713
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 56
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:39:57 Warning: Warning (4096): Argument 1 passed to Cake\Controller\Controller::beforeFilter() must be an instance of Cake\Event\Event, none given, called in C:\xampp\htdocs\assignment\src\Controller\AppController.php on line 56 and defined in [C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php, line 713]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
Cake\Controller\Controller::beforeFilter() - CORE\src\Controller\Controller.php, line 713
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 56
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:40:22 Warning: Warning (4096): Argument 1 passed to Cake\Controller\Controller::beforeFilter() must be an instance of Cake\Event\Event, none given, called in C:\xampp\htdocs\assignment\src\Controller\AppController.php on line 56 and defined in [C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php, line 713]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
Cake\Controller\Controller::beforeFilter() - CORE\src\Controller\Controller.php, line 713
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 56
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 14:40:23 Warning: Warning (4096): Argument 1 passed to Cake\Controller\Controller::beforeFilter() must be an instance of Cake\Event\Event, none given, called in C:\xampp\htdocs\assignment\src\Controller\AppController.php on line 56 and defined in [C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php, line 713]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
Cake\Controller\Controller::beforeFilter() - CORE\src\Controller\Controller.php, line 713
App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 56
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 12
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 15:06:52 Error: Fatal Error (4): syntax error, unexpected 'login' (T_STRING), expecting ']' in [C:\xampp\htdocs\assignment\src\Controller\UsersController.php, line 16]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 15:06:53 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'login' (T_STRING), expecting ']'
Request URL: /assignment/users/login
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 16)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 15:34:55 Error: Fatal Error (1): Call to undefined method Cake\Controller\Component\AuthComponent::login() in [C:\xampp\htdocs\assignment\src\Controller\UsersController.php, line 48]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 15:34:56 Error: [Cake\Error\FatalErrorException] Call to undefined method Cake\Controller\Component\AuthComponent::login()
Request URL: /assignment/users/login
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 15:36:29 Error: Fatal Error (1): Call to undefined method Cake\Controller\Component\AuthComponent::login() in [C:\xampp\htdocs\assignment\src\Controller\UsersController.php, line 48]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 15:36:30 Error: [Cake\Error\FatalErrorException] Call to undefined method Cake\Controller\Component\AuthComponent::login()
Request URL: /assignment/users/login
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 15:51:30 Error: [Cake\Controller\Exception\MissingComponentException] Component class SessionComponent could not be found.
Exception Attributes: array (
  'class' => 'SessionComponent',
  'plugin' => NULL,
)
Request URL: /assignment/users/login
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Core\ObjectRegistry.php(91): Cake\Controller\ComponentRegistry->_throwMissingClassError('Session', NULL)
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(321): Cake\Core\ObjectRegistry->load('Session', Array)
#2 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(462): Cake\Controller\Controller->loadComponent('Session', Array)
#3 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(265): Cake\Controller\Controller->_loadComponents()
#4 [internal function]: Cake\Controller\Controller->__construct(Object(Cake\Network\Request), Object(Cake\Network\Response), 'Users')
#5 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Filter\ControllerFactoryFilter.php(90): ReflectionClass->newInstance(Object(Cake\Network\Request), Object(Cake\Network\Response), 'Users')
#6 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Filter\ControllerFactoryFilter.php(49): Cake\Routing\Filter\ControllerFactoryFilter->_getController(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\DispatcherFilter.php(145): Cake\Routing\Filter\ControllerFactoryFilter->beforeDispatch(Object(Cake\Event\Event))
#8 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Event\EventManager.php(389): Cake\Routing\DispatcherFilter->handle(Object(Cake\Event\Event), Object(Cake\Network\Request), Object(Cake\Network\Response))
#9 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#10 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#11 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(62): Cake\Routing\Dispatcher->dispatchEvent('Dispatcher.befo...', Array)
#12 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-07 15:52:46 Error: [Cake\Controller\Exception\MissingComponentException] Component class SessionComponent could not be found.
Exception Attributes: array (
  'class' => 'SessionComponent',
  'plugin' => NULL,
)
Request URL: /assignment/users/login
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Core\ObjectRegistry.php(91): Cake\Controller\ComponentRegistry->_throwMissingClassError('Session', NULL)
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(321): Cake\Core\ObjectRegistry->load('Session', Array)
#2 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(462): Cake\Controller\Controller->loadComponent('Session', Array)
#3 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(265): Cake\Controller\Controller->_loadComponents()
#4 [internal function]: Cake\Controller\Controller->__construct(Object(Cake\Network\Request), Object(Cake\Network\Response), 'Users')
#5 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Filter\ControllerFactoryFilter.php(90): ReflectionClass->newInstance(Object(Cake\Network\Request), Object(Cake\Network\Response), 'Users')
#6 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Filter\ControllerFactoryFilter.php(49): Cake\Routing\Filter\ControllerFactoryFilter->_getController(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\DispatcherFilter.php(145): Cake\Routing\Filter\ControllerFactoryFilter->beforeDispatch(Object(Cake\Event\Event))
#8 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Event\EventManager.php(389): Cake\Routing\DispatcherFilter->handle(Object(Cake\Event\Event), Object(Cake\Network\Request), Object(Cake\Network\Response))
#9 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#10 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#11 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(62): Cake\Routing\Dispatcher->dispatchEvent('Dispatcher.befo...', Array)
#12 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-07 15:52:53 Error: [Cake\Controller\Exception\MissingComponentException] Component class SessionComponent could not be found.
Exception Attributes: array (
  'class' => 'SessionComponent',
  'plugin' => NULL,
)
Request URL: /assignment/users
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Core\ObjectRegistry.php(91): Cake\Controller\ComponentRegistry->_throwMissingClassError('Session', NULL)
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(321): Cake\Core\ObjectRegistry->load('Session', Array)
#2 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(462): Cake\Controller\Controller->loadComponent('Session', Array)
#3 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(265): Cake\Controller\Controller->_loadComponents()
#4 [internal function]: Cake\Controller\Controller->__construct(Object(Cake\Network\Request), Object(Cake\Network\Response), 'Users')
#5 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Filter\ControllerFactoryFilter.php(90): ReflectionClass->newInstance(Object(Cake\Network\Request), Object(Cake\Network\Response), 'Users')
#6 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Filter\ControllerFactoryFilter.php(49): Cake\Routing\Filter\ControllerFactoryFilter->_getController(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\DispatcherFilter.php(145): Cake\Routing\Filter\ControllerFactoryFilter->beforeDispatch(Object(Cake\Event\Event))
#8 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Event\EventManager.php(389): Cake\Routing\DispatcherFilter->handle(Object(Cake\Event\Event), Object(Cake\Network\Request), Object(Cake\Network\Response))
#9 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#10 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#11 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(62): Cake\Routing\Dispatcher->dispatchEvent('Dispatcher.befo...', Array)
#12 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-07 15:56:16 Error: Fatal Error (4): syntax error, unexpected '}', expecting ')' in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 62]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 15:56:17 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '}', expecting ')'
Request URL: /assignment/users
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 62)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 15:56:53 Error: [Cake\Controller\Exception\MissingComponentException] Component class SessionComponent could not be found.
Exception Attributes: array (
  'class' => 'SessionComponent',
  'plugin' => NULL,
)
Request URL: /assignment/users
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Core\ObjectRegistry.php(91): Cake\Controller\ComponentRegistry->_throwMissingClassError('Session', NULL)
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(321): Cake\Core\ObjectRegistry->load('Session', Array)
#2 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(462): Cake\Controller\Controller->loadComponent('Session', Array)
#3 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php(265): Cake\Controller\Controller->_loadComponents()
#4 [internal function]: Cake\Controller\Controller->__construct(Object(Cake\Network\Request), Object(Cake\Network\Response), 'Users')
#5 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Filter\ControllerFactoryFilter.php(90): ReflectionClass->newInstance(Object(Cake\Network\Request), Object(Cake\Network\Response), 'Users')
#6 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Filter\ControllerFactoryFilter.php(49): Cake\Routing\Filter\ControllerFactoryFilter->_getController(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\DispatcherFilter.php(145): Cake\Routing\Filter\ControllerFactoryFilter->beforeDispatch(Object(Cake\Event\Event))
#8 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Event\EventManager.php(389): Cake\Routing\DispatcherFilter->handle(Object(Cake\Event\Event), Object(Cake\Network\Request), Object(Cake\Network\Response))
#9 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#10 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#11 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(62): Cake\Routing\Dispatcher->dispatchEvent('Dispatcher.befo...', Array)
#12 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-07 15:58:07 Warning: Warning (4096): Argument 1 passed to Cake\Controller\Controller::beforeFilter() must be an instance of Cake\Event\Event, none given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 9 and defined in [C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php, line 713]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
Cake\Controller\Controller::beforeFilter() - CORE\src\Controller\Controller.php, line 713
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 9
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 15:58:09 Error: [Cake\Controller\Exception\MissingActionException] Action UsersController::index() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'index',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /assignment/users
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#2 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-11-07 15:58:10 Warning: Warning (4096): Argument 1 passed to Cake\Controller\Controller::beforeFilter() must be an instance of Cake\Event\Event, none given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 9 and defined in [C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php, line 713]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
Cake\Controller\Controller::beforeFilter() - CORE\src\Controller\Controller.php, line 713
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 9
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 15:58:10 Error: [Cake\Controller\Exception\MissingActionException] Action UsersController::index() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'index',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /assignment/users
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#2 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-11-07 15:58:45 Warning: Warning (4096): Argument 1 passed to Cake\Controller\Controller::beforeFilter() must be an instance of Cake\Event\Event, none given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 13 and defined in [C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php, line 713]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
Cake\Controller\Controller::beforeFilter() - CORE\src\Controller\Controller.php, line 713
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 13
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 15:58:54 Warning: Warning (4096): Argument 1 passed to Cake\Controller\Controller::beforeFilter() must be an instance of Cake\Event\Event, none given, called in C:\xampp\htdocs\assignment\src\Controller\UsersController.php on line 13 and defined in [C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Controller\Controller.php, line 713]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 139
Cake\Controller\Controller::beforeFilter() - CORE\src\Controller\Controller.php, line 713
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 13
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 478
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-07 16:33:55 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 59]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-07 16:33:56 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '}'
Request URL: /assignment/users/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 59)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-07 16:39:35 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Users could not be found.
Exception Attributes: array (
  'class' => 'Users',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /assignment/users/add
Stack Trace:
#0 C:\xampp\htdocs\assignment\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-09 02:35:05 Error: Fatal Error (4): syntax error, unexpected '*' in [C:\xampp\htdocs\assignment\src\Controller\UsersController.php, line 24]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-09 02:35:06 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '*'
Request URL: /assignment/users/login
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-09 05:51:55 Error: Fatal Error (1): Class 'App\Controller\Controller' not found in [C:\xampp\htdocs\assignment\src\Controller\AppController.php, line 28]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 192
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 91
[main] - [internal], line ??



2015-11-09 05:51:59 Error: [Cake\Error\FatalErrorException] Class 'App\Controller\Controller' not found
Request URL: /assignment/users/login
Stack Trace:
#0 C:\xampp\htdocs\assignment\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(91): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'App\\Cont...', 'C:\\xampp\\htdocs...', 28)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


